use crate::*;
use Size::*;
use Pos::*;
use keru_draw::parley::Alignment;

// todo remove this
// TODO: Re-add Cap and Join when implementing stroke features in keru_draw
#[allow(dead_code)]
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum Cap {
    Butt,
    Round,
    Square,
}

#[allow(dead_code)]
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum Join {
    Miter,
    Round,
    Bevel,
}

// todo: not very discoverable from docs. there's a list of constants on the main page, maybe that's good? link to that or something?

pub const ICON_RIGHT: &[u8] = include_bytes!("svg_icons/right.svg");
pub const ICON_LEFT: &[u8] = include_bytes!("svg_icons/left.svg");
pub const ICON_PLUS: &[u8] = include_bytes!("svg_icons/plus.svg");
pub const ICON_MINUS: &[u8] = include_bytes!("svg_icons/minus.svg");
pub const ICON_DELETE: &[u8] = include_bytes!("svg_icons/delete.svg");
pub const ICON_EDIT: &[u8] = include_bytes!("svg_icons/pencil.svg");
const DEBUG_ONLY_SHAPE: Shape = Shape::Rectangle { rounded_corners: RoundedCorners::ALL, corner_radius: DEFAULT_CORNER_RADIUS };

/// [`Node`] for a node_root_params.
pub(crate) const NODE_ROOT_PARAMS: Node = Node {
    animation: NO_ANIMATION,
    key: None,
    text_options: TextOptions::const_default(),
    children_layout: ChildrenLayout::Free,
    visible: false,
    stroke: None,
    color: ColorFill2::Color(Color::TRANSPARENT),
    shape: Shape::Rectangle { rounded_corners: RoundedCorners::ALL, corner_radius: DEFAULT_CORNER_RADIUS },
    blur: None,
    shadow: None,
    second_shadow: None,
    interact: Interact {
        senses: Sense::NONE,
        absorbs_mouse_events: false,
        click_animation: false,
        focus_indicator: true,
        focusable: true,
    },
    layout: Layout {
        size: Xy::new_symm(Size::Frac(1.0)),
        padding: Xy::new_symm(0.0),
        position: Xy::new_symm(Start),
        anchor: Xy::new_symm(Anchor::Start),
        scrollable: Xy::new(false, false),
        pos_origin_x: HorizontalOrigin::Left,
        pos_origin_y: VerticalOrigin::Top,
    },
    children_can_hide: ChildrenCanHide::Inherit,
    clip_children: Xy::new(false, false),
    transform: Transform::IDENTITY,
    custom_render: false,
    z_index: 0.0,
    grid_element: GridElement::ONE_BY_ONE,
    free_placement: false,
    constant: false,
    ignore_parent_scroll: false,
    text: None,
    placeholder_text: None,
    image: None,
    image_options: ImageOptions::DEFAULT,
    text_alignment: Alignment::Center,
    vertical_text_alignment: VerticalTextAlignment::Center,
    text_size: None,
    text_color: None,
    text_properties: &[],
    text_style_flags: TextStyleFlags::empty(),
};
/// [`Node`] for a default.
pub const DEFAULT: Node = Node {
    animation: NO_ANIMATION,
    key: None,
    text_options: TextOptions::const_default(),
    children_layout: ChildrenLayout::Free,
    visible: true,
    stroke: None,
    color: ColorFill2::Color(Color::KERU_BLUE),
    shape: Shape::Rectangle { rounded_corners: RoundedCorners::ALL, corner_radius: DEFAULT_CORNER_RADIUS },
    blur: None,
    shadow: None,
    second_shadow: None,
    interact: Interact {
        senses: Sense::NONE,
        absorbs_mouse_events: false,
        click_animation: false,
        focus_indicator: true,
        focusable: true,
    },
    layout: Layout {
        size: Xy::new_symm(Size::Frac(1.0)),
        padding: Xy::new_symm(0.0),
        position: Xy::new_symm(Center),
        anchor: Xy::new_symm(Anchor::Start),
        scrollable: Xy::new(false, false),
        pos_origin_x: HorizontalOrigin::Left,
        pos_origin_y: VerticalOrigin::Top,
    },
    children_can_hide: ChildrenCanHide::Inherit,
    clip_children: Xy::new(false, false),
    transform: Transform::IDENTITY,
    custom_render: false,
    z_index: 0.0,
    grid_element: GridElement::ONE_BY_ONE,
    free_placement: false,
    constant: false,
    ignore_parent_scroll: false,
    text: None,
    placeholder_text: None,
    image: None,
    image_options: ImageOptions::DEFAULT,
    text_alignment: Alignment::Center,
    vertical_text_alignment: VerticalTextAlignment::Center,
    text_size: None,
    text_color: None,
    text_properties: &[],
    text_style_flags: TextStyleFlags::empty(),
};
/// [`Node`] for a vertical stack.
pub const V_STACK: Node = Node {
    animation: NO_ANIMATION,
    key: None,
    text_options: TextOptions::const_default(),
    children_layout: ChildrenLayout::Stack {
        arrange: Arrange::Center,
        axis: Axis::Y,
        spacing: 8.0,
    },
    visible: true,
    color: ColorFill2::Color(Color::TRANSPARENT),
    stroke: None,
    shape: DEBUG_ONLY_SHAPE,
    blur: None,
    shadow: None,
    second_shadow: None,
    interact: Interact {
        senses: Sense::NONE,
        absorbs_mouse_events: false,
        click_animation: false,
        focus_indicator: true,
        focusable: true,
    },
    layout: Layout {
        size: Xy::new(Size::FitContent, Size::FitContent),
        padding: Xy::new_symm(0.0),
        position: Xy::new_symm(Center),
        anchor: Xy::new_symm(Anchor::Start),
        scrollable: Xy::new(false, false),
        pos_origin_x: HorizontalOrigin::Left,
        pos_origin_y: VerticalOrigin::Top,
    },
    children_can_hide: ChildrenCanHide::Inherit,
    clip_children: Xy::new(false, false),
    transform: Transform::IDENTITY,
    custom_render: false,
    z_index: 0.0,
    grid_element: GridElement::ONE_BY_ONE,
    free_placement: false,
    constant: false,
    ignore_parent_scroll: false,
    text: None,
    placeholder_text: None,
    image: None,
    image_options: ImageOptions::DEFAULT,
    text_alignment: Alignment::Center,
    vertical_text_alignment: VerticalTextAlignment::Center,
    text_size: None,
    text_color: None,
    text_properties: &[],
    text_style_flags: TextStyleFlags::empty(),
};
/// [`Node`] for a horizontal stack.
pub const H_STACK: Node = Node {
    animation: NO_ANIMATION,
    key: None,
    text_options: TextOptions::const_default(),
    children_layout: ChildrenLayout::Stack {
        arrange: Arrange::Center,
        axis: Axis::X,
        spacing: 8.0,
    },
    visible: true,
    color: ColorFill2::Color(Color::TRANSPARENT),
    stroke: None,
    shape: DEBUG_ONLY_SHAPE,
    blur: None,
    shadow: None,
    second_shadow: None,
    interact: Interact {
        senses: Sense::NONE,
        absorbs_mouse_events: false,
        click_animation: false,
        focus_indicator: true,
        focusable: true,
    },
    layout: Layout {
        size: Xy::new(Size::FitContent, Size::FitContent),
        padding: Xy::new_symm(0.0),
        position: Xy::new_symm(Center),
        anchor: Xy::new_symm(Anchor::Start),
        scrollable: Xy::new(false, false),
        pos_origin_x: HorizontalOrigin::Left,
        pos_origin_y: VerticalOrigin::Top,
    },
    children_can_hide: ChildrenCanHide::Inherit,
    clip_children: Xy::new(false, false),
    transform: Transform::IDENTITY,
    custom_render: false,
    z_index: 0.0,
    grid_element: GridElement::ONE_BY_ONE,
    free_placement: false,
    constant: false,
    ignore_parent_scroll: false,
    text: None,
    placeholder_text: None,
    image: None,
    image_options: ImageOptions::DEFAULT,
    text_alignment: Alignment::Center,
    vertical_text_alignment: VerticalTextAlignment::Center,
    text_size: None,
    text_color: None,
    text_properties: &[],
    text_style_flags: TextStyleFlags::empty(),
};

/// [`Node`] for a vertically scrollable vertical stack.
pub const V_SCROLL_STACK: Node = Node {
    animation: NO_ANIMATION,
    key: None,
    text_options: TextOptions::const_default(),
    children_layout: ChildrenLayout::Stack {
        arrange: Arrange::Start,
        axis: Axis::Y,
        spacing: 10.0,
    },
    visible: true,
    color: ColorFill2::Color(Color::TRANSPARENT),
    stroke: None,
    shape: DEBUG_ONLY_SHAPE,
    blur: None,
    shadow: None,
    second_shadow: None,
    interact: Interact {
        senses: Sense::NONE,
        absorbs_mouse_events: false,
        click_animation: false,
        focus_indicator: true,
        focusable: true,
    },
    layout: Layout {
        size: Xy::new(Size::FitContent, Size::Fill),
        padding: Xy::new_symm(0.0),
        position: Xy::new_symm(Center),
        anchor: Xy::new_symm(Anchor::Start),
        scrollable: Xy::new(false, true),
        pos_origin_x: HorizontalOrigin::Left,
        pos_origin_y: VerticalOrigin::Top,
    },
    children_can_hide: ChildrenCanHide::Inherit,
    clip_children: Xy::new(false, true),
    transform: Transform::IDENTITY,
    custom_render: false,
    z_index: 0.0,
    grid_element: GridElement::ONE_BY_ONE,
    free_placement: false,
    constant: false,
    ignore_parent_scroll: false,
    text: None,
    placeholder_text: None,
    image: None,
    image_options: ImageOptions::DEFAULT,
    text_alignment: Alignment::Center,
    vertical_text_alignment: VerticalTextAlignment::Center,
    text_size: None,
    text_color: None,
    text_properties: &[],
    text_style_flags: TextStyleFlags::empty(),
};


/// [`Node`] for a vertically scrollable vertical stack.
pub const H_SCROLL_STACK: Node = Node {
    animation: NO_ANIMATION,
    key: None,
    text_options: TextOptions::const_default(),
    children_layout: ChildrenLayout::Stack {
        arrange: Arrange::Start,
        axis: Axis::X,
        spacing: 10.0,
    },
    visible: true,
    color: ColorFill2::Color(Color::TRANSPARENT),
    stroke: None,
    shape: DEBUG_ONLY_SHAPE,
    blur: None,
    shadow: None,
    second_shadow: None,
    interact: Interact {
        senses: Sense::NONE,
        absorbs_mouse_events: false,
        click_animation: false,
        focus_indicator: true,
        focusable: true,
    },
    layout: Layout {
        size: Xy::new(Size::Fill, Size::FitContent),
        padding: Xy::new_symm(0.0),
        position: Xy::new_symm(Center),
        anchor: Xy::new_symm(Anchor::Start),
        scrollable: Xy::new(true, false),
        pos_origin_x: HorizontalOrigin::Left,
        pos_origin_y: VerticalOrigin::Top,
    },
    children_can_hide: ChildrenCanHide::Inherit,
    clip_children: Xy::new(true, false),
    transform: Transform::IDENTITY,
    custom_render: false,
    z_index: 0.0,
    grid_element: GridElement::ONE_BY_ONE,
    free_placement: false,
    constant: false,
    ignore_parent_scroll: false,
    text: None,
    placeholder_text: None,
    image: None,
    image_options: ImageOptions::DEFAULT,
    text_alignment: Alignment::Center,
    vertical_text_alignment: VerticalTextAlignment::Center,
    text_size: None,
    text_color: None,
    text_properties: &[],
    text_style_flags: TextStyleFlags::empty(),
};

/// [`Node`] for a margin.
pub const MARGIN: Node = Node {
    animation: NO_ANIMATION,
    key: None,
    children_layout: ChildrenLayout::Free,
    text_options: TextOptions::const_default(),
    visible: true,
        color: ColorFill2::Color(Color::TRANSPARENT),
    stroke: None,
    shape: DEBUG_ONLY_SHAPE,
    blur: None,
    shadow: None,
    second_shadow: None,
    interact: Interact {
        senses: Sense::NONE,
        absorbs_mouse_events: false,
        click_animation: false,
        focus_indicator: true,
        focusable: true,
    },
    layout: Layout {
        size: Xy::new_symm(Size::Frac(0.9)),
        padding: Xy::new_symm(0.0),
        position: Xy::new_symm(Center),
        anchor: Xy::new_symm(Anchor::Start),
        scrollable: Xy::new(false, false),
        pos_origin_x: HorizontalOrigin::Left,
        pos_origin_y: VerticalOrigin::Top,
    },
    children_can_hide: ChildrenCanHide::Inherit,
    clip_children: Xy::new(false, false),
    transform: Transform::IDENTITY,
    custom_render: false,
    z_index: 0.0,
    grid_element: GridElement::ONE_BY_ONE,
    free_placement: false,
    constant: false,
    ignore_parent_scroll: false,
    text: None,
    placeholder_text: None,
    image: None,
    image_options: ImageOptions::DEFAULT,
    text_alignment: Alignment::Center,
    vertical_text_alignment: VerticalTextAlignment::Center,
    text_size: None,
    text_color: None,
    text_properties: &[],
    text_style_flags: TextStyleFlags::empty(),
};
/// [`Node`] for an icon button.
pub const ICON_BUTTON: Node = Node {
    animation: NO_ANIMATION,
    key: None,
    children_layout: ChildrenLayout::Free,
    text_options: TextOptions::const_default(),
    visible: true,
    stroke: None,
    color: ColorFill2::Color(Color::WHITE),
    shape: Shape::Rectangle { rounded_corners: RoundedCorners::ALL, corner_radius: 0.0 },
    blur: None,
    shadow: None,
    second_shadow: None,
    interact: Interact {
        senses: Sense::CLICK.union(Sense::CLICK_RELEASE),
        absorbs_mouse_events: true,
        click_animation: true,
        focus_indicator: true,
        focusable: true,
    },
    layout: Layout {
        size: Xy::new_symm(Size::Pixels(40.0)),
        padding: Xy::new_symm(2.0),
        position: Xy::new_symm(Center),
        anchor: Xy::new_symm(Anchor::Start),
        scrollable: Xy::new(false, false),
        pos_origin_x: HorizontalOrigin::Left,
        pos_origin_y: VerticalOrigin::Top,
    },
    children_can_hide: ChildrenCanHide::Inherit,
    clip_children: Xy::new(false, false),
    transform: Transform::IDENTITY,
    custom_render: false,
    z_index: 0.0,
    grid_element: GridElement::ONE_BY_ONE,
    free_placement: false,
    constant: false,
    ignore_parent_scroll: false,
    text: None,
    placeholder_text: None,
    image: None,
    image_options: ImageOptions::DEFAULT,
    text_alignment: Alignment::Center,
    vertical_text_alignment: VerticalTextAlignment::Center,
    text_size: None,
    text_color: None,
    text_properties: &[],
    text_style_flags: TextStyleFlags::empty(),
};
/// [`Node`] for an image. 
pub const IMAGE: Node = Node {
    animation: NO_ANIMATION,
    key: None,
    children_layout: ChildrenLayout::Free,
    text_options: TextOptions::const_default(),
    visible: true,
    stroke: None,
    color: ColorFill2::Color(Color::WHITE),
    shape: Shape::Rectangle { rounded_corners: RoundedCorners::ALL, corner_radius: DEFAULT_CORNER_RADIUS },
    blur: None,
    shadow: None,
    second_shadow: None,
    interact: Interact {
        senses: Sense::NONE,
        absorbs_mouse_events: true,
        click_animation: false,
        focus_indicator: true,
        focusable: true,
    },
    layout: Layout {
        size: Xy::new_symm(FitContent),
        padding: Xy::new_symm(0.0),
        position: Xy::new_symm(Center),
        anchor: Xy::new_symm(Anchor::Start),
        scrollable: Xy::new(false, false),
        pos_origin_x: HorizontalOrigin::Left,
        pos_origin_y: VerticalOrigin::Top,
    },
    children_can_hide: ChildrenCanHide::Inherit,
    clip_children: Xy::new(false, false),
    transform: Transform::IDENTITY,
    custom_render: false,
    z_index: 0.0,
    grid_element: GridElement::ONE_BY_ONE,
    free_placement: false,
    constant: false,
    ignore_parent_scroll: false,
    text: None,
    placeholder_text: None,
    image: None,
    image_options: ImageOptions::DEFAULT,
    text_alignment: Alignment::Center,
    vertical_text_alignment: VerticalTextAlignment::Center,
    text_size: None,
    text_color: None,
    text_properties: &[],
    text_style_flags: TextStyleFlags::empty(),
};
/// [`Node`] for an icon button. 
pub const IMAGE_BUTTON: Node = Node {
    animation: NO_ANIMATION,
    key: None,
    children_layout: ChildrenLayout::Free,
    text_options: TextOptions::const_default(),
    visible: true,
    stroke: None,
    color: ColorFill2::Color(Color::WHITE),
    shape: Shape::Rectangle { rounded_corners: RoundedCorners::ALL, corner_radius: DEFAULT_CORNER_RADIUS },
    blur: None,
    shadow: None,
    second_shadow: None,
    interact: Interact {
        senses: Sense::CLICK.union(Sense::CLICK_RELEASE),
        absorbs_mouse_events: true,
        click_animation: true,
        focus_indicator: true,
        focusable: true,
    },
    layout: Layout {
        size: Xy::new_symm(FitContent),
        padding: Xy::new_symm(0.0),
        position: Xy::new_symm(Center),
        anchor: Xy::new_symm(Anchor::Start),
        scrollable: Xy::new(false, false),
        pos_origin_x: HorizontalOrigin::Left,
        pos_origin_y: VerticalOrigin::Top,
    },
    children_can_hide: ChildrenCanHide::Inherit,
    clip_children: Xy::new(false, false),
    transform: Transform::IDENTITY,
    custom_render: false,
    z_index: 0.0,
    grid_element: GridElement::ONE_BY_ONE,
    free_placement: false,
    constant: false,
    ignore_parent_scroll: false,
    text: None,
    placeholder_text: None,
    image: None,
    image_options: ImageOptions::DEFAULT,
    text_alignment: Alignment::Center,
    vertical_text_alignment: VerticalTextAlignment::Center,
    text_size: None,
    text_color: None,
    text_properties: &[],
    text_style_flags: TextStyleFlags::empty(),
};
/// [`Node`] for a button. 
pub const BUTTON: Node = Node {
    animation: NO_ANIMATION,
    key: None,
    children_layout: ChildrenLayout::Free,
    text_options: TextOptions {
        single_line: true,
        editable: false,
        selectable: false,
        edit_disabled: false,
        auto_markdown: false,
        use_pointer_comparison: false,
    },
    visible: true,
    stroke: None,
    color: ColorFill2::Color(Color::KERU_PINK),
    shape: Shape::Rectangle { rounded_corners: RoundedCorners::ALL, corner_radius: DEFAULT_CORNER_RADIUS },
    blur: None,
    shadow: None,
    second_shadow: None,
    interact: Interact {
        senses: Sense::CLICK.union(Sense::CLICK_RELEASE),
        absorbs_mouse_events: true,
        click_animation: true,
        focus_indicator: true,
        focusable: true,
    },
    layout: Layout {
        size: Xy::new_symm(FitContent),
        padding: Xy::new_symm(10.0),
        position: Xy::new_symm(Center),
        anchor: Xy::new_symm(Anchor::Start),
        scrollable: Xy::new(false, false),
        pos_origin_x: HorizontalOrigin::Left,
        pos_origin_y: VerticalOrigin::Top,
    },
    children_can_hide: ChildrenCanHide::Inherit,
    clip_children: Xy::new(false, false),
    transform: Transform::IDENTITY,
    custom_render: false,
    z_index: 0.0,
    grid_element: GridElement::ONE_BY_ONE,
    free_placement: false,
    constant: false,
    ignore_parent_scroll: false,
    text: None,
    placeholder_text: None,
    image: None,
    image_options: ImageOptions::DEFAULT,
    text_alignment: Alignment::Center,
    vertical_text_alignment: VerticalTextAlignment::Center,
    text_size: None,
    text_color: None,
    text_properties: &[],
    text_style_flags: TextStyleFlags::empty(),
};
/// [`Node`] for a label. 
pub const LABEL: Node = Node {
    animation: NO_ANIMATION,
    key: None,
    children_layout: ChildrenLayout::Free,
    text_options: TextOptions {
        single_line: true,
        editable: false,
        selectable: true,
        edit_disabled: false,
        auto_markdown: false,
        use_pointer_comparison: false,
    },
    visible: true,
    stroke: None,
    color: ColorFill2::Color(Color::KERU_BLUE),
    shape: Shape::Rectangle { rounded_corners: RoundedCorners::ALL, corner_radius: DEFAULT_CORNER_RADIUS },
    blur: None,
    shadow: None,
    second_shadow: None,
    interact: Interact {
        senses: Sense::NONE,
        absorbs_mouse_events: true,
        click_animation: false,
        focus_indicator: true,
        focusable: true,
    },
    layout: Layout {
        size: Xy::new_symm(FitContent),
        padding: Xy::new_symm(10.0),
        position: Xy::new_symm(Center),
        anchor: Xy::new_symm(Anchor::Start),
        scrollable: Xy::new(false, false),
        pos_origin_x: HorizontalOrigin::Left,
        pos_origin_y: VerticalOrigin::Top,
    },
    children_can_hide: ChildrenCanHide::Inherit,
    clip_children: Xy::new(false, false),
    transform: Transform::IDENTITY,
    custom_render: false,
    z_index: 0.0,
    grid_element: GridElement::ONE_BY_ONE,
    free_placement: false,
    constant: false,
    ignore_parent_scroll: false,
    text: None,
    placeholder_text: None,
    image: None,
    image_options: ImageOptions::DEFAULT,
    text_alignment: Alignment::Center,
    vertical_text_alignment: VerticalTextAlignment::Center,
    text_size: None,
    text_color: None,
    text_properties: &[],
    text_style_flags: TextStyleFlags::empty(),
};

/// [`Node`] for a label containing a multi-line paragraph. 
pub const MULTILINE_LABEL: Node = Node {
    animation: NO_ANIMATION,
    key: None,
    children_layout: ChildrenLayout::Free,
    text_options: TextOptions {
        single_line: false,
        editable: false,
        selectable: true,
        edit_disabled: false,
        auto_markdown: false,
        use_pointer_comparison: false,
    },
    visible: true,
    stroke: None,
    color: ColorFill2::Color(Color::KERU_BLUE),
    shape: Shape::Rectangle { rounded_corners: RoundedCorners::ALL, corner_radius: DEFAULT_CORNER_RADIUS },
    blur: None,
    shadow: None,
    second_shadow: None,
    interact: Interact {
        senses: Sense::NONE,
        absorbs_mouse_events: true,
        click_animation: false,
        focus_indicator: true,
        focusable: true,
    },
    layout: Layout {
        size: Xy::new_symm(FitContent),
        padding: Xy::new_symm(10.0),
        position: Xy::new_symm(Center),
        anchor: Xy::new_symm(Anchor::Start),
        scrollable: Xy::new(false, false),
        pos_origin_x: HorizontalOrigin::Left,
        pos_origin_y: VerticalOrigin::Top,
    },
    children_can_hide: ChildrenCanHide::Inherit,
    clip_children: Xy::new(false, false),
    transform: Transform::IDENTITY,
    custom_render: false,
    z_index: 0.0,
    grid_element: GridElement::ONE_BY_ONE,
    free_placement: false,
    constant: false,
    ignore_parent_scroll: false,
    text: None,
    placeholder_text: None,
    image: None,
    image_options: ImageOptions::DEFAULT,
    text_alignment: Alignment::Center,
    vertical_text_alignment: VerticalTextAlignment::Center,
    text_size: None,
    text_color: None,
    text_properties: &[],
    text_style_flags: TextStyleFlags::empty(),
};

/// [`Node`] for a text element. 
pub const TEXT: Node = Node {
    animation: NO_ANIMATION,
    key: None,
    children_layout: ChildrenLayout::Free,
    text_options: TextOptions {
        single_line: true,
        editable: false,
        selectable: true,
        edit_disabled: false,
        auto_markdown: false,
        use_pointer_comparison: false,
    },
    visible: true,
        color: ColorFill2::Color(Color::TRANSPARENT),
    stroke: None,
    shape: DEBUG_ONLY_SHAPE,
    blur: None,
    shadow: None,
    second_shadow: None,
    interact: Interact {
        senses: Sense::NONE,
        absorbs_mouse_events: false,
        click_animation: false,
        focus_indicator: true,
        focusable: true,
    },
    layout: Layout {
        size: Xy::new_symm(FitContent),
        padding: Xy::new_symm(2.0),
        position: Xy::new_symm(Center),
        anchor: Xy::new_symm(Anchor::Start),
        scrollable: Xy::new(false, false),
        pos_origin_x: HorizontalOrigin::Left,
        pos_origin_y: VerticalOrigin::Top,
    },
    children_can_hide: ChildrenCanHide::Inherit,
    clip_children: Xy::new(false, false),
    transform: Transform::IDENTITY,
    custom_render: false,
    z_index: 0.0,
    grid_element: GridElement::ONE_BY_ONE,
    free_placement: false,
    constant: false,
    ignore_parent_scroll: false,
    text: None,
    placeholder_text: None,
    image: None,
    image_options: ImageOptions::DEFAULT,
    text_alignment: Alignment::Center,
    vertical_text_alignment: VerticalTextAlignment::Center,
    text_size: None,
    text_color: None,
    text_properties: &[],
    text_style_flags: TextStyleFlags::empty(),
};

/// [`Node`] for an icon element.
pub const ICON: Node = Node {
    animation: NO_ANIMATION,
    key: None,
    children_layout: ChildrenLayout::Free,
    text_options: TextOptions::const_default(),
    visible: true,
    stroke: None,
    color: ColorFill2::Color(Color::WHITE),
    shape: Shape::Rectangle { rounded_corners: RoundedCorners::ALL, corner_radius: 0.0 },
    blur: None,
    shadow: None,
    second_shadow: None,
    interact: Interact {
        senses: Sense::NONE,
        absorbs_mouse_events: false,
        click_animation: false,
        focus_indicator: true,
        focusable: true,
    },
    layout: Layout {
        size: Xy::new_symm(Size::Pixels(40.0)),
        padding: Xy::new_symm(2.0),
        position: Xy::new_symm(Center),
        anchor: Xy::new_symm(Anchor::Start),
        scrollable: Xy::new(false, false),
        pos_origin_x: HorizontalOrigin::Left,
        pos_origin_y: VerticalOrigin::Top,
    },
    children_can_hide: ChildrenCanHide::Inherit,
    clip_children: Xy::new(false, false),
    transform: Transform::IDENTITY,
    custom_render: false,
    z_index: 0.0,
    grid_element: GridElement::ONE_BY_ONE,
    free_placement: false,
    constant: false,
    ignore_parent_scroll: false,
    text: None,
    placeholder_text: None,
    image: None,
    image_options: ImageOptions::DEFAULT,
    text_alignment: Alignment::Center,
    vertical_text_alignment: VerticalTextAlignment::Center,
    text_size: None,
    text_color: None,
    text_properties: &[],
    text_style_flags: TextStyleFlags::empty(),
};

/// [`Node`] for a multiline text edit box. 
pub const TEXT_EDIT: Node = Node {
    animation: NO_ANIMATION,
    key: None,
    children_layout: ChildrenLayout::Free,
    text_options: TextOptions {
        single_line: false,
        editable: true,
        selectable: true,
        edit_disabled: false,
        auto_markdown: false,
        use_pointer_comparison: false,
    },
    visible: true,
    stroke: None,
    color: ColorFill2::Color(Color::GREY),
    shape: Shape::Rectangle { rounded_corners: RoundedCorners::ALL, corner_radius: DEFAULT_CORNER_RADIUS },
    blur: None,
    shadow: None,
    second_shadow: None,
    interact: Interact {
        senses: Sense::CLICK,
        absorbs_mouse_events: true,
        click_animation: true,
        focus_indicator: true,
        focusable: true,
    },
    layout: Layout {
        size: Xy::new_symm(FitContent),
        padding: Xy::new_symm(10.0),
        position: Xy::new_symm(Center),
        anchor: Xy::new_symm(Anchor::Start),
        scrollable: Xy::new(false, false),
        pos_origin_x: HorizontalOrigin::Left,
        pos_origin_y: VerticalOrigin::Top,
    },
    children_can_hide: ChildrenCanHide::Inherit,
    clip_children: Xy::new(false, false),
    transform: Transform::IDENTITY,
    custom_render: false,
    z_index: 0.0,
    grid_element: GridElement::ONE_BY_ONE,
    free_placement: false,
    constant: false,
    ignore_parent_scroll: false,
    text: None,
    placeholder_text: None,
    image: None,
    image_options: ImageOptions::DEFAULT,
    text_alignment: Alignment::Start,
    vertical_text_alignment: VerticalTextAlignment::Top,
    text_size: None,
    text_color: None,
    text_properties: &[],
    text_style_flags: TextStyleFlags::empty(),
};

/// [`Node`] for a single line text edit box. 
pub const TEXT_EDIT_LINE: Node = Node {
    animation: NO_ANIMATION,
    key: None,
    children_layout: ChildrenLayout::Free,
    text_options: TextOptions {
        single_line: true,
        editable: true,
        selectable: true,
        edit_disabled: false,
        auto_markdown: false,
        use_pointer_comparison: false,
    },
    visible: true,
    stroke: None,
    color: ColorFill2::Color(Color::GREY),
    shape: Shape::Rectangle { rounded_corners: RoundedCorners::ALL, corner_radius: DEFAULT_CORNER_RADIUS },
    blur: None,
    shadow: None,
    second_shadow: None,
    interact: Interact {
        senses: Sense::NONE,
        absorbs_mouse_events: true,
        click_animation: true,
        focus_indicator: true,
        focusable: true,
    },
    layout: Layout {
        size: Xy::new_symm(FitContent),
        padding: Xy::new_symm(10.0),
        position: Xy::new_symm(Center),
        anchor: Xy::new_symm(Anchor::Start),
        scrollable: Xy::new(false, false),
        pos_origin_x: HorizontalOrigin::Left,
        pos_origin_y: VerticalOrigin::Top,
    },
    children_can_hide: ChildrenCanHide::Inherit,
    clip_children: Xy::new(false, false),
    transform: Transform::IDENTITY,
    custom_render: false,
    z_index: 0.0,
    grid_element: GridElement::ONE_BY_ONE,
    free_placement: false,
    constant: false,
    ignore_parent_scroll: false,
    text: None,
    placeholder_text: None,
    image: None,
    image_options: ImageOptions::DEFAULT,
    text_alignment: Alignment::Start,
    vertical_text_alignment: VerticalTextAlignment::Center,
    text_size: None,
    text_color: None,
    text_properties: &[],
    text_style_flags: TextStyleFlags::empty(),
};

/// [`Node`] for a text element containing a multi-line paragraph.
pub const TEXT_PARAGRAPH: Node = Node {
    animation: NO_ANIMATION,
    key: None,
    children_layout: ChildrenLayout::Free,
    text_options: TextOptions {
        single_line: false,
        editable: false,
        selectable: true,
        edit_disabled: false,
        auto_markdown: false,
        use_pointer_comparison: false,
    },
    visible: true,
        color: ColorFill2::Color(Color::TRANSPARENT),
    stroke: None,
    shape: DEBUG_ONLY_SHAPE,
    blur: None,
    shadow: None,
    second_shadow: None,
    interact: Interact {
        senses: Sense::NONE,
        absorbs_mouse_events: false,
        click_animation: false,
        focus_indicator: true,
        focusable: true,
    },
    layout: Layout {
        size: Xy::new_symm(FitContent),
        padding: Xy::new_symm(2.0),
        position: Xy::new_symm(Center),
        anchor: Xy::new_symm(Anchor::Start),
        scrollable: Xy::new(false, false),
        pos_origin_x: HorizontalOrigin::Left,
        pos_origin_y: VerticalOrigin::Top,
    },
    children_can_hide: ChildrenCanHide::Inherit,
    clip_children: Xy::new(false, false),
    transform: Transform::IDENTITY,
    custom_render: false,
    z_index: 0.0,
    grid_element: GridElement::ONE_BY_ONE,
    free_placement: false,
    constant: false,
    ignore_parent_scroll: false,
    text: None,
    placeholder_text: None,
    image: None,
    image_options: ImageOptions::DEFAULT,
    text_alignment: Alignment::Center,
    vertical_text_alignment: VerticalTextAlignment::Center,
    text_size: None,
    text_color: None,
    text_properties: &[],
    text_style_flags: TextStyleFlags::empty(),
};

/// [`Node`] for a panel. 
pub const PANEL: Node = Node {
    animation: NO_ANIMATION,
    key: None,
    children_layout: ChildrenLayout::Free,
    text_options: TextOptions::const_default(),
    visible: true,
    stroke: None,
    color: ColorFill2::Color(Color::KERU_PINK),
    shape: Shape::Rectangle { rounded_corners: RoundedCorners::ALL, corner_radius: DEFAULT_CORNER_RADIUS },
    blur: None,
    shadow: None,
    second_shadow: None,
    interact: Interact {
        senses: Sense::NONE,
        absorbs_mouse_events: true,
        click_animation: false,
        focus_indicator: true,
        focusable: true,
    },
    layout: Layout {
        size: Xy::new_symm(FitContent),
        padding: Xy::new_symm(10.0),
        position: Xy::new_symm(Center),
        anchor: Xy::new_symm(Anchor::Start),
        scrollable: Xy::new(false, false),
        pos_origin_x: HorizontalOrigin::Left,
        pos_origin_y: VerticalOrigin::Top,
    },
    children_can_hide: ChildrenCanHide::Inherit,
    clip_children: Xy::new(false, false),
    transform: Transform::IDENTITY,
    custom_render: false,
    z_index: 0.0,
    grid_element: GridElement::ONE_BY_ONE,
    free_placement: false,
    constant: false,
    ignore_parent_scroll: false,
    text: None,
    placeholder_text: None,
    image: None,
    image_options: ImageOptions::DEFAULT,
    text_alignment: Alignment::Center,
    vertical_text_alignment: VerticalTextAlignment::Center,
    text_size: None,
    text_color: None,
    text_properties: &[],
    text_style_flags: TextStyleFlags::empty(),
};

/// [`Node`] for a container. 
pub const CONTAINER: Node = Node {
    animation: NO_ANIMATION,
    key: None,
    children_layout: ChildrenLayout::Free,
    text_options: TextOptions::const_default(),
    visible: false,
    stroke: None,
    color: ColorFill2::Color(Color::TRANSPARENT),
    shape: Shape::Rectangle { rounded_corners: RoundedCorners::ALL, corner_radius: DEFAULT_CORNER_RADIUS },
    blur: None,
    shadow: None,
    second_shadow: None,
    interact: Interact {
        senses: Sense::NONE,
        absorbs_mouse_events: false,
        click_animation: false,
        focus_indicator: true,
        focusable: true,
    },
    layout: Layout {
        size: Xy::new_symm(FitContent),
        padding: Xy::new_symm(10.0),
        position: Xy::new_symm(Center),
        anchor: Xy::new_symm(Anchor::Start),
        scrollable: Xy::new(false, false),
        pos_origin_x: HorizontalOrigin::Left,
        pos_origin_y: VerticalOrigin::Top,
    },
    children_can_hide: ChildrenCanHide::Inherit,
    clip_children: Xy::new(false, false),
    transform: Transform::IDENTITY,
    custom_render: false,
    z_index: 0.0,
    grid_element: GridElement::ONE_BY_ONE,
    free_placement: false,
    constant: false,
    ignore_parent_scroll: false,
    text: None,
    placeholder_text: None,
    image: None,
    image_options: ImageOptions::DEFAULT,
    text_alignment: Alignment::Center,
    vertical_text_alignment: VerticalTextAlignment::Center,
    text_size: None,
    text_color: None,
    text_properties: &[],
    text_style_flags: TextStyleFlags::empty(),
};

pub const BOTTOM_LEFT: Node = CONTAINER
    .padding(15.0)
    .position_x(Pos::Start)
    .position_y(Pos::End)
    .stack_arrange(Arrange::End)
    .size_symm(Size::FitContent);

pub const BOTTOM_RIGHT: Node = CONTAINER
    .padding(15.0)
    .position_x(Pos::Start)
    .position_y(Pos::End)
    .stack_arrange(Arrange::End)
    .size_symm(Size::FitContent);

pub const TOP_LEFT: Node = CONTAINER
    .padding(15.0)
    .position_x(Pos::Start)
    .position_y(Pos::Start)
    .stack_arrange(Arrange::End)
    .size_symm(Size::FitContent);

pub const TOP_RIGHT: Node = CONTAINER
    .padding(15.0)
    .position_x(Pos::End)
    .position_y(Pos::Start)
    .stack_arrange(Arrange::End)
    .size_symm(Size::FitContent);

/// [`Node`] for a custom rendered node.
/// 
/// Use [`UiNode::render_rect`] to get the render data for your node, then render it in a separate draw call.
/// ```no_run
/// # use keru::*; use keru::node_library::*; let mut ui: Ui = unimplemented!();
/// #
/// #[node_key] const CUSTOM_RENDERED_NODE: NodeKey;
/// let render_rect = ui.get_node(CUSTOM_RENDERED_NODE).unwrap().render_rect();
/// ```
pub const CUSTOM_RENDERED_PANEL: Node = Node {
    animation: NO_ANIMATION,
    key: None,
    children_layout: ChildrenLayout::Free,
    text_options: TextOptions::const_default(),
    visible: false,
    stroke: None,
    color: ColorFill2::Color(Color::GREENSCREEN),
    shape: Shape::Rectangle { rounded_corners: RoundedCorners::ALL, corner_radius: DEFAULT_CORNER_RADIUS },
    blur: None,
    shadow: None,
    second_shadow: None,
    interact: Interact {
        senses: Sense::NONE,
        absorbs_mouse_events: true,
        click_animation: false,
        focus_indicator: true,
        focusable: true,
    },
    layout: Layout {
        size: Xy::new_symm(FitContent),
        padding: Xy::new_symm(0.0),
        position: Xy::new_symm(Center),
        anchor: Xy::new_symm(Anchor::Start),
        scrollable: Xy::new(false, false),
        pos_origin_x: HorizontalOrigin::Left,
        pos_origin_y: VerticalOrigin::Top,
    },
    children_can_hide: ChildrenCanHide::Inherit,
    clip_children: Xy::new(false, false),
    transform: Transform::IDENTITY,
    custom_render: false,
    z_index: 0.0,
    grid_element: GridElement::ONE_BY_ONE,
    free_placement: false,
    constant: false,
    ignore_parent_scroll: false,
    text: None,
    placeholder_text: None,
    image: None,
    image_options: ImageOptions::DEFAULT,
    text_alignment: Alignment::Center,
    vertical_text_alignment: VerticalTextAlignment::Center,
    text_size: None,
    text_color: None,
    text_properties: &[],
    text_style_flags: TextStyleFlags::empty(),
};

/// [`Node`] for a spacer element.
pub const SPACER: Node = Node {
    animation: NO_ANIMATION,
    key: None,
    children_layout: ChildrenLayout::Free,
    text_options: TextOptions::const_default(),
    visible: true,
        color: ColorFill2::Color(Color::TRANSPARENT),
    stroke: None,
    shape: DEBUG_ONLY_SHAPE,
    blur: None,
    shadow: None,
    second_shadow: None,
    interact: Interact {
        senses: Sense::NONE,
        absorbs_mouse_events: false,
        click_animation: false,
        focus_indicator: true,
        focusable: true,
    },
    layout: Layout {
        size: Xy::new_symm(Fill),
        padding: Xy::new_symm(0.0),
        position: Xy::new_symm(Center),
        anchor: Xy::new_symm(Anchor::Start),
        scrollable: Xy::new(false, false),
        pos_origin_x: HorizontalOrigin::Left,
        pos_origin_y: VerticalOrigin::Top,
    },
    children_can_hide: ChildrenCanHide::Inherit,
    clip_children: Xy::new(false, false),
    transform: Transform::IDENTITY,
    custom_render: false,
    z_index: 0.0,
    grid_element: GridElement::ONE_BY_ONE,
    free_placement: false,
    constant: false,
    ignore_parent_scroll: false,
    text: None,
    placeholder_text: None,
    image: None,
    image_options: ImageOptions::DEFAULT,
    text_alignment: Alignment::Center,
    vertical_text_alignment: VerticalTextAlignment::Center,
    text_size: None,
    text_color: None,
    text_properties: &[],
    text_style_flags: TextStyleFlags::empty(),
};

/// [`Node`] for a invisible spacer element that fills all the available space in the X direction.
pub const H_SPACER: Node = Node {
    animation: NO_ANIMATION,
    key: None,
    children_layout: ChildrenLayout::Free,
    text_options: TextOptions::const_default(),
        color: ColorFill2::Color(Color::TRANSPARENT),
    stroke: None,
    shape: DEBUG_ONLY_SHAPE,
    blur: None,
    shadow: None,
    second_shadow: None,
    visible: true,
    interact: Interact {
        senses: Sense::NONE,
        absorbs_mouse_events: false,
        click_animation: false,
        focus_indicator: true,
        focusable: true,
    },
    layout: Layout {
        size: Xy::new(Size::Fill, Size::FitContent),
        padding: Xy::new_symm(0.0),
        position: Xy::new_symm(Center),
        anchor: Xy::new_symm(Anchor::Start),
        scrollable: Xy::new(false, false),
        pos_origin_x: HorizontalOrigin::Left,
        pos_origin_y: VerticalOrigin::Top,
    },
    children_can_hide: ChildrenCanHide::Inherit,
    clip_children: Xy::new(false, false),
    transform: Transform::IDENTITY,
    custom_render: false,
    z_index: 0.0,
    grid_element: GridElement::ONE_BY_ONE,
    free_placement: false,
    constant: false,
    ignore_parent_scroll: false,
    text: None,
    placeholder_text: None,
    image: None,
    image_options: ImageOptions::DEFAULT,
    text_alignment: Alignment::Center,
    vertical_text_alignment: VerticalTextAlignment::Center,
    text_size: None,
    text_color: None,
    text_properties: &[],
    text_style_flags: TextStyleFlags::empty(),
};

/// [`Node`] for a invisible spacer element that fills all the available space in the Y direction.
pub const V_SPACER: Node = Node {
    animation: NO_ANIMATION,
    key: None,
    children_layout: ChildrenLayout::Free,
    text_options: TextOptions::const_default(),
    visible: true,
        color: ColorFill2::Color(Color::TRANSPARENT),
    stroke: None,
    shape: DEBUG_ONLY_SHAPE,
    blur: None,
    shadow: None,
    second_shadow: None,
    interact: Interact {
        senses: Sense::NONE,
        absorbs_mouse_events: false,
        click_animation: false,
        focus_indicator: true,
        focusable: true,
    },
    layout: Layout {
        size: Xy::new(Size::FitContent, Size::Fill),
        padding: Xy::new_symm(0.0),
        position: Xy::new_symm(Center),
        anchor: Xy::new_symm(Anchor::Start),
        scrollable: Xy::new(false, false),
        pos_origin_x: HorizontalOrigin::Left,
        pos_origin_y: VerticalOrigin::Top,
    },
    children_can_hide: ChildrenCanHide::Inherit,
    clip_children: Xy::new(false, false),
    transform: Transform::IDENTITY,
    custom_render: false,
    z_index: 0.0,
    grid_element: GridElement::ONE_BY_ONE,
    free_placement: false,
    constant: false,
    ignore_parent_scroll: false,
    text: None,
    placeholder_text: None,
    image: None,
    image_options: ImageOptions::DEFAULT,
    text_alignment: Alignment::Center,
    vertical_text_alignment: VerticalTextAlignment::Center,
    text_size: None,
    text_color: None,
    text_properties: &[],
    text_style_flags: TextStyleFlags::empty(),
};

/// [`Node`] for a grid layout.
pub const GRID: Node = Node {
    animation: NO_ANIMATION,
    key: None,
    text_options: TextOptions::const_default(),
    children_layout: ChildrenLayout::Grid {
        columns: MainAxisCellSize::Count(3),
        spacing_x: 8.0,
        spacing_y: 8.0,
        flow: GridFlow::DEFAULT,
    },
    visible: true,
    color: ColorFill2::Color(Color::TRANSPARENT),
    stroke: None,
    shape: DEBUG_ONLY_SHAPE,
    blur: None,
    shadow: None,
    second_shadow: None,
    interact: Interact {
        senses: Sense::NONE,
        absorbs_mouse_events: false,
        click_animation: false,
        focus_indicator: true,
        focusable: true,
    },
    layout: Layout {
        size: Xy::new(Size::FitContent, Size::FitContent),
        padding: Xy::new_symm(0.0),
        position: Xy::new_symm(Center),
        anchor: Xy::new_symm(Anchor::Start),
        scrollable: Xy::new(false, false),
        pos_origin_x: HorizontalOrigin::Left,
        pos_origin_y: VerticalOrigin::Top,
    },
    children_can_hide: ChildrenCanHide::Inherit,
    clip_children: Xy::new(false, false),
    transform: Transform::IDENTITY,
    custom_render: false,
    z_index: 0.0,
    grid_element: GridElement::ONE_BY_ONE,
    free_placement: false,
    constant: false,
    ignore_parent_scroll: false,
    text: None,
    placeholder_text: None,
    image: None,
    image_options: ImageOptions::DEFAULT,
    text_alignment: Alignment::Center,
    vertical_text_alignment: VerticalTextAlignment::Center,
    text_size: None,
    text_color: None,
    text_properties: &[],
    text_style_flags: TextStyleFlags::empty(),
};

/// [`Node`] for a horizontal divider line.
pub const H_LINE: Node = Node {
    animation: NO_ANIMATION,
    key: None,
    children_layout: ChildrenLayout::Free,
    text_options: TextOptions::const_default(),
    visible: true,
    stroke: Some(Stroke {
        width: 2.0,
        color: ColorFill2::Color(Color::WHITE),
        dash_length: 0.0,
        dash_offset: 0.0,
    }),
    color: ColorFill2::Color(Color::WHITE),
    shape: Shape::Segment { start: (0.0, 0.0), end: (1.0, 1.0), dash_length: None },
    blur: None,
    shadow: None,
    second_shadow: None,
    interact: Interact {
        senses: Sense::NONE,
        absorbs_mouse_events: false,
        click_animation: false,
        focus_indicator: true,
        focusable: true,
    },
    layout: Layout {
        size: Xy::new(Size::Fill, Size::Pixels(0.0)),
        padding: Xy::new_symm(0.0),
        position: Xy::new_symm(Center),
        anchor: Xy::new_symm(Anchor::Start),
        scrollable: Xy::new(false, false),
        pos_origin_x: HorizontalOrigin::Left,
        pos_origin_y: VerticalOrigin::Top,
    },
    children_can_hide: ChildrenCanHide::Inherit,
    clip_children: Xy::new(false, false),
    transform: Transform::IDENTITY,
    custom_render: false,
    z_index: 0.0,
    grid_element: GridElement::ONE_BY_ONE,
    free_placement: false,
    constant: false,
    ignore_parent_scroll: false,
    text: None,
    placeholder_text: None,
    image: None,
    image_options: ImageOptions::DEFAULT,
    text_alignment: Alignment::Center,
    vertical_text_alignment: VerticalTextAlignment::Center,
    text_size: None,
    text_color: None,
    text_properties: &[],
    text_style_flags: TextStyleFlags::empty(),
};

/// fake node used to keep track of components.
pub(crate) const COMPONENT_ROOT: Node = Node {
    animation: Animation { speed: 1.0, enter: EnterAnimation::None, exit: ExitAnimation::None, state_transition: StateTransition { animate_position: true } },
    key: None,
    children_layout: ChildrenLayout::Free,
    text_options: TextOptions::const_default(),
    visible: false,
    stroke: None,
    color: ColorFill2::Color(Color::DEBUG_BLUE),
    shape: Shape::Rectangle { rounded_corners: RoundedCorners::ALL, corner_radius: DEFAULT_CORNER_RADIUS },
    blur: None,
    shadow: None,
    second_shadow: None,
    interact: Interact {
        senses: Sense::NONE,
        absorbs_mouse_events: false,
        click_animation: false,
        focus_indicator: true,
        focusable: true,
    },
    layout: Layout {
        size: Xy::new_symm(FitContent),
        padding: Xy::new_symm(0.0),
        position: Xy::new_symm(Center),
        anchor: Xy::new_symm(Anchor::Start),
        scrollable: Xy::new(false, false),
        pos_origin_x: HorizontalOrigin::Left,
        pos_origin_y: VerticalOrigin::Top,
    },
    children_can_hide: ChildrenCanHide::Inherit,
    clip_children: Xy::new(false, false),
    transform: Transform::IDENTITY,
    custom_render: false,
    z_index: 0.0,
    grid_element: GridElement::ONE_BY_ONE,
    free_placement: true,
    constant: false,
    ignore_parent_scroll: false,
    text: None,
    placeholder_text: None,
    image: None,
    image_options: ImageOptions::DEFAULT,
    text_alignment: Alignment::Center,
    vertical_text_alignment: VerticalTextAlignment::Center,
    text_size: None,
    text_color: None,
    text_properties: &[],
    text_style_flags: TextStyleFlags::empty(),
};
